Presentation/ElectronicsStore/Controllers/ComponentController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.App;
namespace Store.Web.Controllers
{
    public class ComponentController : Controller
    {
        private readonly ComponentService componentService;
        public ComponentController(ComponentService componentService)
        {
            this.componentService = componentService;
        }

        public async Task<IActionResult> Index(int id)
        {
            var model = await componentService.GetByIdAsync(id);

            return View(model);
        }
    }
}

Presentation/ElectronicsStore/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.App;
namespace Store.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly ComponentService componentService;

        public SearchController(ComponentService componentService)
        {
            this.componentService = componentService;
        }

        public async Task<IActionResult> Index(string query)
        {
            var components = await componentService.GetAllByQueryAsync(query);
            return View("Index", components);
        }
    }
}

Presentation/ElectronicsStore/Views/Search/Index.cshtml
@model IReadOnlyCollection<ComponentModel>

@{
    ViewData["Title"] = "Результаты поиска";
}

<h1>Результаты поиска</h1>

@if (Model.Count == 0)
{
    <p>Ничего не найдено.</p>
}
else
{
    <ul>
    @foreach (var component in Model)
    {
            <li><a href="@Url.Action("Index", "Component", new { id = component.Id })">@component.NameOfComponent</a></li>
    }
    </ul>
}